// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Session-mode pooler — migrations/introspection need a non-transaction-mode
    // connection. The running app uses DATABASE_URL instead, via lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
